test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.a5ced524d5026bd15daf5f7647395212ae3c09b8.name = "Upgrade from 0.11.9"
    test_upgrade_from.7a4833633f76d050296c783e565f8cdfc913c75a.name = "Upgrade from 0.11.2"
